function vrednost = BiharmonicniOperator(u,x,y,h)
    vrednost = 1/h.^4 *(20*u(x,y) - 8*(u(x+h,y) + u(x-h,y) + u(x,y+h) + u(x,y-h))...
        + 2*(u(x+h,y+h) + u(x-h,y+h) + u(x-h,y-h) + u(x+h,y-h))...
        + u(x+2*h,y) + u(x-2*h,y) + u(x,y+2*h) + u(x,y-2*h));
end
